#!/bin/sh
set -e

# Automatically added by dh_python3:
if which py3compile >/dev/null 2>&1; then
	py3compile  -p  python3-xlines
fi

# copy configuration files to local
cp /usr/local/lib/xlines/config/*.list /home/$SUDO_USER/.config/xlines/

# End automatically added section
