#!/usr/bin/env bash

# copy configuration files to local
if [ $SUDO_USER ] && [ ! -d "/home/$SUDO_USER/.config/xlines" ]; then

	mkdir "/home/$SUDO_USER/.config/xlines"
	chown -R $SUDO_USER:$SUDO_USER  "/home/$SUDO_USER/.config/xlines"

elif [ ! -d "/home/$USER/.config/xlines" ]; then

	mkdir "/home/$USER/.config/xlines"

fi

exit 0

# <-- end preinstall -->
